future: true
permalink: /:title/
url: http://Leeegal.github.io
name: Lee G
author: G Lee
qq: 1016545929
email: liguo6@mail2.sysu.edu.cn

duoshuo: Lee G
beian: 
cnzz: 
weibo: 吾有一弟名柳生
github: Leegal
about: "这里是 Lee G 的个人博客，创建于 2018 年。"

safe: true
paginate: 20
