future: true
permalink: /:title/
url: http://Leeegal.github.io
name: Lee G
author: 果哥
qq: 1016545929
email: liguo6@mail2.sysu.edu.cn
duoshuo: 果哥
beian: 
cnzz: 
weibo: 吾有一弟名柳生
github: Leeegal
paginate: 20
highlighter: rouge
truncate: true
about: "果哥(Leeegal)"
