future: true
permalink: /:title/
url: http://Latitude.github.io
name: Latitude-Lee 
author: 李伟杜
qq: 1016545929
email: liguo6@mail2.sysu.edu.cn
duoshuo: 李伟杜
beian: 
cnzz: 
weibo: 
github: Latitude
paginate: 20
highlighter: rouge
truncate: true
about: "李伟杜（Latitude）"
